import '../globals.css';
import Head from 'next/head';
import Header from '../../components/app/header';
import Footer from '../../components/app/footer';
import Providers from '../../components/provider/Providers';
import { NanumSquare, NanumSquareOTF } from '../../fonts/fonts';

export default function RootLayout({ children, lang }) {
    const metadata = {
        title: 'Create Next App',
        description: 'Generated by create next app',
    };

    return (
        <html
            lang={lang}
            className={
                lang === 'ko' ? NanumSquare.className : NanumSquareOTF.className
            }
            suppressHydrationWarning
        >
            <Head>
                <title>{metadata.title}</title>
                <meta name="description" content={metadata.description} />
                <link rel="icon" type="image/x-icon" href="/favicon.ico" />
            </Head>
            <body>
                <Providers>
                    <Header lang={lang} />
                    {children}
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
